# Generated by Django 4.0.1 on 2022-03-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('idCredito', models.CharField(max_length=10)),
                ('Valor', models.CharField(max_length=10)),
                ('plazo', models.PositiveIntegerField()),
                ('Cuota', models.CharField(max_length=10)),
            ],
        ),
    ]
