# Generated by Django 4.0.1 on 2022-03-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deudores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Cuota',
            new_name='cuota',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='Valor',
            new_name='valor',
        ),
    ]
