# Generated by Django 4.0.1 on 2022-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deudores', '0002_rename_cuota_cliente_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plazo',
            field=models.CharField(max_length=2),
        ),
    ]
